Bionessori/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bionessori.Models;
using Bionessori.Core;
using Bionessori.Core.Interfaces;
using System.Security.Policy;

namespace Bionessori.Controllers {
    /// <summary>
    /// Контроллер описывает работу с роутами ERP-системы.
    /// </summary>
    public class RouteController : Controller {
        // Метод перенаправляет на главную страницу ведения объектов.
        public IActionResult Index() {
            //ViewData["Title"] = "Главная страница - Ведение объектов";

            return View();
        }

        // Метод возвращает на главную страницу.
        [Route("index")]
        public IActionResult RouteIndex() {
            return View("Index");
        }

        // Метод перенаправляет на страницу со списком карт пациентов.       
        [Route("card")]
        public IActionResult RouteCard() {
            ViewData["Title"] = "Электронные медицинские карты пациентов - Список карт пациентов";

            return View();
        }

        // Метод переходит на страницу администратора.
        [Route("admin")]
        public IActionResult RouteAdmin() {
            ViewData["Title"] = "Панель администратора";

            return View();
        }

        // Метод переходит на страницу MRP.
        [Route("mrp")]
        public IActionResult RouteMRP() {
            ViewData["Title"] = "Планирование потребностей в материалах";

            return View();
        }

        // Метод переходит на страницу со списком всех заявок в MRP.
        [Route("view/request")]
        public IActionResult GetRequests() {
            ViewData["Title"] = "Планирование потребностей в материалах - Список заявок";

            return View();
        }

        // Метод переходит на страницу со списком материалов.
        [Route("view/material")]
        public IActionResult GetMaterials() {
            ViewData["Title"] = "Ведение объектов номенклатуры";

            return View();
        }

        // Переходит к созданию новой заявки на потребности в материалах.
        [Route("create-request")]
        public IActionResult CreateRequest() {
            ViewData["Title"] = "Планирование потребностей в материалах - Создание новой заявки";

            return View();
        }

        // Переходит на страницу создания карты пациента.
        [Route("create-card")]
        public IActionResult RouteCreateCard() {
            ViewData["Title"] = "Ведение электронных карт пациентов - Создание новой карты пациента";

            return View();
        }

        // Переходит на страницу просмотра карты пациента.
        [Route("get-card")]
        public IActionResult RouteGetCard() {
            ViewData["Title"] = "Ведение электронных карт пациентов - Просмотр карты пациента";

            return View();
        }

        // Переходит на страницу редактирования карты пациента.
        [Route("edit-card")]
        public IActionResult RouteEditCard() {
            ViewData["Title"] = "Ведение электронных карт пациентов - Редактирование карты пациента";

            return View();
        }

        // Метод переходит на страницу просмотра заявки.
        [Route("view-request")]
        public IActionResult GetRequest() {
            ViewData["Title"] = "Планирование потребностей в материалах - Просмотр заявки";

            return View();
        }

        // Метод переходит на страницу редактирования заявки.
        [Route("edit-request")]
        public IActionResult RouteEditRequest() {
            ViewData["Title"] = "Планирование потребностей в материалах - Редактирование заявки";

            return View();
        }

        // Метод переходит на страницу регистратуры.
        [Route("registry")]
        public IActionResult RouteRegistry() {
            ViewData["Title"] = "Ведение объектов регистратуры";

            return View();
        }

        // Метод переходит на страницу записи пациента на прием к врачу.
        [Route("add-registry")]
        public IActionResult AddRegistry() {
            ViewData["Title"] = "Ведение объектов регистратуры - Запись пациента на прием";

            return View();
        }

        // Метод переходит на страницу редактирования записи.
        [Route("edit-reception")]
        public IActionResult EditReception() {
            ViewData["Title"] = "Ведение объектов регистратуры - Редактирование записи пациента на прием";

            return View();
        }

        // Метод переходит на страницу направлений.
        [Route("direction")]
        public IActionResult RouteDirection() {
            ViewData["Title"] = "Ведение объектов регистратуры - Направления";

            return View();
        }

        // Метод переходит на страницу личного кабинета.
        [Route("front-office")]
        public IActionResult RouteFrontOffice() {
            ViewData["Title"] = "Мой профиль";

            return View();
        }

        // Метод переходит на страницу создания направления.
        [Route("create-direction")]
        public IActionResult RouteCreateDirection() {
            ViewData["Title"] = "Ведение объектов регистратуры - Создание направления";

            return View();
        }

        // Метод переходит на страницу редактирования направления.
        [Route("edit-direction")]
        public IActionResult RouteEditDirection() {
            ViewData["Title"] = "Ведение объектов регистратуры - Редактирование направления";

            return View();
        }
       
        // Метод переходит на страницу управления закупками.
        [Route("view-manage-purchases")]
        public IActionResult RouteManagePurchases() {
            ViewData["Title"] = "Ведение объектов управления закупками";

            return View();
        }
        
        // Метод создает номенклатуру.
        [Route("create-nomenclature")]
        public IActionResult CreateNomenclature() {
            ViewData["Title"] = "Номенклатура - Создание номенклатуры";

            return View();
        }

        // Метод переходит на страницу коммерческих предложений.
        [Route("commerce-offer")]
        public IActionResult CommerceOffer() {
            ViewData["Title"] = "Управление закупками - КП (коммерческие предложения)";

            return View();
        }

        // Метод создает коммерческое предложение поставщику.
        [Route("create-commerce-offer")]
        public IActionResult CreateCommerceOffer() {
            ViewData["Title"] = "Управление закупками - Создание коммерческого предложения";

            return View();
        }
    }
}

Bionessori/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link href="~/css/Footer.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="https://unpkg.com/nprogress@0.2.0/nprogress.css" rel="stylesheet" />
</head>
<body>
	<script src="https://unpkg.com/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>
	<script src="https://unpkg.com/nprogress@0.2.0/nprogress.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

	<div class="mask">
		<div class="loader">

		</div>
	</div>

	<div id="app">
		<header>
			<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white mb-5">
				<div class="container">
					<!-- Логотип. -->
					<div class="block-beta">
						<div>
							<a class="navbar-brand" asp-controller="Route" asp-action="Index">
								<img src="~/images/bionessori White.png" height="40" />
							</a>
						</div>

						<div class="beta">
							<span data-toggle="tooltip" title="Beta - означает, что в некоторых случаях работа ERP-системы может быть не стабильной и могут наблюдаться ошибки.
Если вы увидели какую-то ошибку - сообщите об этом через форму обратной связи. Спасибо.
-
С уважением, разработчик ERP-системы Bionessori.">beta</span>
						</div>
					</div>

					<div class="nav-title text-center">
						<span class="text-center">@ViewData["Title"]</span>
					</div>

					<div class="log_check">
						<button type="button" class="btn-item btn btn-default state-log" data-toggle="modal" data-target="#login-modal">Войти</button>

						<button type="button" class="btn-item btn btn-default state-log" data-toggle="modal" data-target="#checkin-modal">Регистрация</button>

						<!-- Выпадающее меню. -->
						<div class="drop-down">
							<button type="button" class="btn-item btn btn-default state" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-user-circle-o" aria-hidden="true"></i>
							</button>
							<div class="drop-menu">
								<span class="mb-1" v-on:click="onRouteFrontOffice"><strong>{{userName}}</strong></span>
								<ul>
									<li>
										<span>Справка</span>
									</li>

									<li v-on:click="onLogOut">
										<span>Выйти</span>
									</li>
								</ul>
							</div>
						</div>

					</div>

					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
				</div>
			</nav>
		</header>

		<footer class="footer text-center">
			<div class="container">
				&copy; 2020 <strong>Bionessori</strong> - <span>Все права защищены.</span>
			</div>
		</footer>

		<!-- Модальное окно авторизации. -->
		<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
			<div id="signin-modal" class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="loginModalLabel">Авторизация</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>

					<div class="modal-body">
						<div class="form-group">
							<input type="text" id="id-sign-login" class="form-control" placeholder="Логин или Email" />
						</div>

						<div class="form-group">
							<input type="password" id="id-sign-password" class="form-control" placeholder="Пароль" />
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn-item btn btn-default" data-dismiss="modal" v-on:click="onSignIn">Войти</button>
						<button type="button" class="btn-item btn btn-default" data-dismiss="modal">Закрыть</button>
					</div>
				</div>
			</div>
		</div>

		<!-- Модальное окно регистрации. -->
		<div class="modal fade" id="checkin-modal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
			<div id="checkin-modall" class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="checkinModalLabel">Регистрация</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>

					<div class="modal-body">
						<div class="form-group">
							<input type="text" id="id-login" class="form-control" placeholder="Логин" />
						</div>

						<div class="form-group">
							<input type="email" id="id-email" class="form-control" placeholder="Email" />
						</div>

						<div class="form-group">
							<input type="number" id="id-number" class="form-control" placeholder="Номер телефона" />
						</div>

						<div class="form-group">
							<input type="password" id="id-password" class="form-control" placeholder="Пароль" />
						</div>

						<div class="form-group">
							<input type="password" id="id-password-repeat" class="form-control" placeholder="Повторите пароль" />
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn-item btn btn-default" data-dismiss="modal" v-on:click="onCheckIn">Регистрация</button>
						<button type="button" class="btn-item btn btn-default" data-dismiss="modal">Закрыть</button>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script src="~/js/RoleMethods.js"></script>
	<script src="~/js/Auth.js"></script>
	<script src="~/js/CommonMethods.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/Loader.js"></script>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	@RenderSection("Scripts", required: false)
</body>
</html>

Bionessori/Views/Shared/_PartialAcceptDeleteRequests.cshtml
@{
	Layout = "_Layout";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@ViewData["Title"]</title>
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Footer.css" rel="stylesheet" />
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>

	<div id="main_mrp">
		<div>
			<div class="col-lg-12">
				<div class="row block-main-info">
					<div class="btn-block-main mb-3 col-lg-12">
						<!-- Левая секция кнопок -->
						<div class="btn-left-block">
							<div class="btns">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="@Url.Action("Index", "Route")">Главная</a></li>

										<li class="breadcrumb-item">
											<a href="@Url.Action("RouteMRP", "Route")">Планирование потребностей в материалах</a>
										</li>

										<li class="breadcrumb-item active" aria-current="page">@ViewData["Data"]</li>
									</ol>
								</nav>
							</div>
						</div>

						<!-- Правая секция кнопок -->
						<div class="btn-right-block">
						
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Секция с новыми заявками. -->
		<div class="row">
			<div class="col-lg-12">
				<h3>Заявки ожидающие подтверждения удаления</h3>
			</div>
		</div>

		<div class="tbl">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Статус
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								№ заявки
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Количество
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Ед.Изм.
							</button>
						</th>
					</tr>
				</thead>

				<tbody>
					<tr id="tbl-item tbl-row-click" class="tbl-item" v-for="el in aAcceptDeleteRequests">
						<td class="text-center req-id">
							{{el.id}}
						</td>

						<td class="text-center">
							<span>{{el.status}}</span>
						</td>

						<td class="text-center">
							<span>{{el.number}}</span>
						</td>

						<td class="text-center">
							<span>{{el.count}}</span>
						</td>

						<td class="text-center">
							<span>{{el.measure}}</span>
						</td>

					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script src="~/js/Route.js"></script>
	<script src="~/js/MRP.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Bionessori/Views/Shared/_PartialInWorkRequests.cshtml
@{
	Layout = "_Layout";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@ViewData["Title"]</title>
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Footer.css" rel="stylesheet" />
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>

	<div id="main_mrp">
		<div>
			<div class="col-lg-12">
				<div class="row block-main-info">
					<div class="btn-block-main mb-3 col-lg-12">
						<!-- Левая секция кнопок -->
						<div class="btn-left-block">
							<div class="btns">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="@Url.Action("Index", "Route")">Главная</a></li>

										<li class="breadcrumb-item">
											<a href="@Url.Action("RouteMRP", "Route")">Планирование потребностей в материалах</a>
										</li>

										<li class="breadcrumb-item active" aria-current="page">@ViewData["Data"]</li>
									</ol>
								</nav>
							</div>
						</div>

						<!-- Правая секция кнопок -->
						<div class="btn-right-block">
					
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Секция с новыми заявками. -->
		<div class="row">
			<div class="col-lg-12">
				<h3>Заявки в работе</h3>
			</div>
		</div>

		<div class="tbl">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Статус
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								№ заявки
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Количество
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Ед.Изм.
							</button>
						</th>
					</tr>
				</thead>

				<tbody>
					<tr id="tbl-item tbl-row-click" class="tbl-item" v-for="el in aInWorkRequests">
						<td class="text-center req-id">
							{{el.id}}
						</td>

						<td class="text-center">
							<span>{{el.status}}</span>
						</td>

						<td class="text-center">
							<span>{{el.number}}</span>
						</td>

						<td class="text-center">
							<span>{{el.count}}</span>
						</td>

						<td class="text-center">
							<span>{{el.measure}}</span>
						</td>

					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script src="~/js/Route.js"></script>
	<script src="~/js/MRP.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Bionessori/Views/Shared/_PartialMappingMaterials.cshtml
@{
	Layout = "_Layout";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@ViewData["Title"]</title>
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Footer.css" rel="stylesheet" />
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>

	<div id="main_mrp">
		<div>
			<div class="col-lg-12">
				<div class="row block-main-info">
					<div class="btn-block-main mb-3 col-lg-12">
						<!-- Левая секция кнопок -->
						<div class="btn-left-block">
							<div class="btns">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="@Url.Action("Index", "Route")">Главная</a></li>

										<li class="breadcrumb-item">
											<a href="@Url.Action("RouteMRP", "Route")">Планирование потребностей в материалах</a>
										</li>

										<li class="breadcrumb-item active" aria-current="page">@ViewData["Data"]</li>
									</ol>
								</nav>
							</div>
						</div>

						<!-- Правая секция кнопок -->
						<div class="btn-right-block">

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Секция с материалами, которые нужно сопоставить. -->
		<div class="row">
			<div class="col-lg-12">
				<h3>Материалы для сопоставления</h3>
			</div>
		</div>

		<div class="tbl">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Статус
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								№ заявки
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Количество
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Ед.Изм.
							</button>
						</th>
					</tr>
				</thead>

				<tbody>
					<tr id="tbl-item tbl-row-click" class="tbl-item" v-for="el in aMappingMaterials">
						<td class="text-center req-id">
							{{el.id}}
						</td>

						<td class="text-center">
							<span>{{el.status}}</span>
						</td>

						<td class="text-center">
							<span>{{el.number}}</span>
						</td>

						<td class="text-center">
							<span>{{el.count}}</span>
						</td>

						<td class="text-center">
							<span>{{el.measure}}</span>
						</td>

					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script src="~/js/Route.js"></script>
	<script src="~/js/MRP.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Bionessori/Views/Shared/_PartialNewRequests.cshtml
@{
	Layout = "_Layout";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@ViewData["Title"]</title>
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Footer.css" rel="stylesheet" />
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>

	<div id="main_mrp">
		<div>
			<div class="col-lg-12">
				<div class="row block-main-info">
					<div class="btn-block-main mb-3 col-lg-12">
						<!-- Левая секция кнопок -->
						<div class="btn-left-block">
							<div class="btns">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="@Url.Action("Index", "Route")">Главная</a></li>

										<li class="breadcrumb-item">
											<a href="@Url.Action("RouteMRP", "Route")">Планирование потребностей в материалах</a>
										</li>

										<li class="breadcrumb-item active" aria-current="page">@ViewData["Data"]</li>
									</ol>
								</nav>
							</div>
						</div>

						<!-- Правая секция кнопок -->
						<div class="btn-right-block">
					
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Секция с новыми заявками. -->
		<div class="row">
			<div class="col-lg-12">
				<h3>Новые заявки</h3>
			</div>
		</div>

		<div class="tbl">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Статус
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								№ заявки
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Количество
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Ед.Изм.
							</button>
						</th>
					</tr>
				</thead>

				<tbody>
					<tr id="tbl-item tbl-row-click" class="tbl-item" v-for="el in aNewRequests">
						<td class="text-center req-id">
							{{el.id}}
						</td>

						<td class="text-center">
							<span>{{el.status}}</span>
						</td>

						<td class="text-center">
							<span>{{el.number}}</span>
						</td>

						<td class="text-center">
							<span>{{el.count}}</span>
						</td>

						<td class="text-center">
							<span>{{el.measure}}</span>
						</td>

					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script src="~/js/Route.js"></script>
	<script src="~/js/MRP.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Bionessori/Views/Shared/_PartialRefillMaterials.cshtml
@{
	Layout = "_Layout";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@ViewData["Title"]</title>
	<link href="~/css/Header.css" rel="stylesheet" />
	<link href="~/css/Main.css" rel="stylesheet" />
	<link href="~/css/Footer.css" rel="stylesheet" />
</head>
<body>
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src="https://use.fontawesome.com/1c903a9a3d.js"></script>

	<div id="main_mrp">
		<div>
			<div class="col-lg-12">
				<div class="row block-main-info">
					<div class="btn-block-main mb-3 col-lg-12">
						<!-- Левая секция кнопок -->
						<div class="btn-left-block">
							<div class="btns">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="@Url.Action("Index", "Route")">Главная</a></li>

										<li class="breadcrumb-item">
											<a href="@Url.Action("RouteMRP", "Route")">Планирование потребностей в материалах</a>
										</li>

										<li class="breadcrumb-item active" aria-current="page">@ViewData["Data"]</li>
									</ol>
								</nav>
							</div>
						</div>

						<!-- Правая секция кнопок -->
						<div class="btn-right-block">

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Секция с материалами, которые нужно пополнить. -->
		<div class="row">
			<div class="col-lg-12">
				<h3>Материалы для пополнения</h3>
			</div>
		</div>

		<div class="tbl">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Статус
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								№ заявки
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Количество
							</button>
						</th>

						<th class="text-center" scope="col">
							<button class="btn btn-link" value="" v-on:click="">
								Ед.Изм.
							</button>
						</th>
					</tr>
				</thead>

				<tbody>
					<tr id="tbl-item tbl-row-click" class="tbl-item" v-for="el in aRefillMaterials">
						<td class="text-center req-id">
							{{el.id}}
						</td>

						<td class="text-center">
							<span>{{el.status}}</span>
						</td>

						<td class="text-center">
							<span>{{el.number}}</span>
						</td>

						<td class="text-center">
							<span>{{el.count}}</span>
						</td>

						<td class="text-center">
							<span>{{el.measure}}</span>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script src="~/js/Route.js"></script>
	<script src="~/js/MRP.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>